### ISSUE TITLE
Why detect Text?

### ISSUE THREAD

**Issue by laiyanyi** [ryanckulp/twitter_ad_blocker#17]
Is it possible to use the symbol(emoji?) before "promoted" text to detect ads? (they seems to using  same pic in different lang)
And is it possible to apply to  "What’s happening" Tab?

**Comment by ryanckulp** [comment]
thanks for the suggestion, i believe you're referring to the "up and to the right" arrow SVG? i'll investigate and respond here.

**Comment by laiyanyi** [comment]
it works well on myside (traditional chinese)

**Comment by Lazza** [comment]
@laiyanyi you gave me a very nice idea for an ad-blocker compatible filter.

Thank you!

https://gist.github.com/Lazza/50af7eb641a0262931bca910c52fc6c6
