### ISSUE TITLE
Promoted tweets showing up

### ISSUE THREAD

**Issue by jmccl** [ryanckulp/twitter_ad_blocker#23]
This worked great for a long time, but now I'm seeing promoted tweets again.

Is there are information you'd like from me to help debug?

**Comment by ryanckulp** [comment]
hey John, thanks for sharing. 

a few "dot" versions back it was indeed temporarily broken. i suspect your Chrome settings might be preventing the Extension auto-update feature, do you mind deleting + reinstalling, then confirming here if you're still seeing ads?

if so, let me know your browser (Chrome, etc), browser version (e.g. Chrome 104.12), and what language you're set to in Twitter. a screenshot could also help (showing ads), maybe you are in a beta for a new feature and the UI elements are slightly different from mine.

Ryan

**Comment by jmccl** [comment]
Sorry, not a bug. Chrome restarted and dropped all of my cookies about a week back. It looks like it also disabled most of my extensions when it did that.
