### ISSUE TITLE
There are now many more divs getting deleted, instead of just the top level post div

### ISSUE THREAD

**Issue by canberranet** [ryanckulp/twitter_ad_blocker#28]
@ryanckulp your latest change has had the unintended side effect of deleting all the divs with the promoted tweets, instead of just the top level one.  
See below, also note you only need the one svg selector and filter on the getAttribute('d')...

`var adsHidden = 0;
var adSelector = "div[data-testid=placementTracking]";
var trendSelector = "div[data-testid=trend]";
var userSelector = "div[data-testid=UserCell]";
var articleSelector = "article[data-testid=tweet]";
var adsSvgPath = 'M19.498 3h-15c-1.381 0-2.5 1.12-2.5 2.5v13c0 1.38 1.119 2.5 2.5 2.5h15c1.381 0 2.5-1.12 2.5-2.5v-13c0-1.38-1.119-2.5-2.5-2.5zm-3.502 12h-2v-3.59l-5.293 5.3-1.414-1.42L12.581 10H8.996V8h7v7z';

function getAds() {
  return Array.from(document.querySelectorAll('path')).filter(s=>s.getAttribute('d').includes(adsSvgPath));
}

function hideAd(ad) {
  if (ad.closest(adSelector) !== null) { // Promoted tweets
    ad.closest(adSelector).remove();
    adsHidden += 1;
  } else if (ad.closest(trendSelector) !== null) {
    ad.closest(trendSelector).remove();
    adsHidden += 1;
  } else if (ad.closest(userSelector) !== null) {
    ad.closest(userSelector).remove();
    adsHidden += 1;
  } else if (ad.closest(articleSelector) !== null) {
    ad.closest(articleSelector).remove();
    adsHidden += 1;
  }

  console.log('Twitter ads hidden: ', adsHidden.toString());
}
// hide ads on page load
document.addEventListener('load', () => getAds().forEach(hideAd));

// oftentimes, tweets render after onload. LCP should catch them.
new PerformanceObserver((entryList) => {
  getAds().forEach(hideAd);
}).observe({type: 'largest-contentful-paint', buffered: true});

// re-check as user scrolls
document.addEventListener('scroll', () => getAds().forEach(hideAd));`

**Comment by canberranet** [comment]
sorry to keep bugging you, but I make extensive use of this extension and want it to work right

**Comment by canberranet** [comment]
OK, so I was not correct, but the youMightLike SVG path has changed to `M12 1.75c-5.11 0-9.25 4.14-9.25 9.25 0 4.77 3.61 8.7 8.25 9.2v2.96l1.15-.17c1.88-.29 4.11-1.56 5.87-3.5 1.79-1.96 3.17-4.69 3.23-7.97.09-5.54-4.14-9.77-9.25-9.77zM13 14H9v-2h4v2zm2-4H9V8h6v2z`

**Comment by canberranet** [comment]
arrgh, there's another one...


var peopleFollowSvgPath = 'M17.863 13.44c1.477 1.58 2.366 3.8 2.632 6.46l.11 1.1H3.395l.11-1.1c.266-2.66 1.155-4.88 2.632-6.46C7.627 11.85 9.648 11 12 11s4.373.85 5.863 2.44zM12 2C9.791 2 8 3.79 8 6s1.791 4 4 4 4-1.79 4-4-1.791-4-4-4z';

} else if (el.getInnerHTML().includes(peopleFollowSvgPath)) {
      filteredAd = el;
    }

this one gets removed by the existing:
var articleSelector = "article[data-testid=tweet]";

**Comment by canberranet** [comment]
I can spend some more time on this on the weekend to try to get it right and do more testing, then will put in a PR.  Sorry for all the noise.

I have a working script I can paste into the console, but it's messy.

**Comment by canberranet** [comment]
> arrgh, there's another one...
> 
> var peopleFollowSvgPath = 'M17.863 13.44c1.477 1.58 2.366 3.8 2.632 6.46l.11 1.1H3.395l.11-1.1c.266-2.66 1.155-4.88 2.632-6.46C7.627 11.85 9.648 11 12 11s4.373.85 5.863 2.44zM12 2C9.791 2 8 3.79 8 6s1.791 4 4 4 4-1.79 4-4-1.791-4-4-4z';
> 
> } else if (el.getInnerHTML().includes(peopleFollowSvgPath)) { filteredAd = el; }
> 
> this one gets removed by the existing: var articleSelector = "article[data-testid=tweet]";

um, this one I'm not sure about... sometimes I like seeing these tweets, other times not.  Maybe can make it configurable?

**Comment by ryanckulp** [comment]
thanks @canberranet for digging into this! please do make a PR and try avoiding a second filtering [here](https://github.com/ryanckulp/twitter_ad_blocker/blob/master/content.js#L25) (inside definition only).

i'll try your new SVG path now. have to bump the version again anyways as Chrome rejected our latest submission due to the "browser action" linking to my website.

**Comment by canberranet** [comment]
@mousavian yes it's removing posts that people you follow liked.  Probably should turn it off.

**Comment by ryanckulp** [comment]
thanks @mousavian, @canberranet, PR-ing to remove this now with a comment on how to add it back.

essentially our next major release here should be a small config panel that opens when click the browser icon.
