### ISSUE TITLE
Does not work with languages other than English

### ISSUE THREAD

**Issue by munierujp** [ryanckulp/twitter_ad_blocker#3]
The label text for Promoted Tweets depends on the user's language setting.
Therefore, this extension will not work with languages other than English.

<img width="1454" alt="スクリーンショット 2021-01-31 11 30 15" src="https://user-images.githubusercontent.com/20086673/106372896-b7dfe200-63b7-11eb-9f92-e147ff8ef17b.png">

## How to resolve

Include label text for each language as follows.

```js
const PROMOTED_LABELS = [
  // for English
  'Promoted',
  // for Japanese
  'プロモーション',
  // TODO: Add other languages
]

function getAds() {
  return Array.from(document.querySelectorAll('span')).filter(el => PROMOTED_LABELS.includes(el.textContent));
}
```

**Comment by ryanckulp** [comment]
@munierujp thanks! great find. i'm using Korean on my phone but not the web, so didn't spot this. will add a few more languages and merge. note, it takes a few days for Chrome to deploy new versions.

**Comment by ryanckulp** [comment]
@munierujp finally pushed this - was waiting for a Korean ad to appear and it took awhile! Chrome will deploy in 1-3 days, you can also import from source here. thanks again!

**Comment by munierujp** [comment]
@ryanckulp Thank you 😄
