### ISSUE TITLE
el.getInnerHTML() doesn't work in Orion

### ISSUE THREAD

**Issue by markphilpot** [ryanckulp/twitter_ad_blocker#41]
`getInnerHTML()` seems to be a funciton only supported by Chrome.  Changing `el.getInnerHTML()` with `el.innerHTML` allows the extension to work in Orion.

https://developer.mozilla.org/en-US/docs/Web/API/Element/innerHTML

**Comment by ryanckulp** [comment]
@markphilpot thanks for spotting and, i'm not sure why we ever used `getInnerHTML` in the first place. fixed via https://github.com/ryanckulp/twitter_ad_blocker/commit/0474920af90f68802eb6bbcb456792bbac67a83e
