### ISSUE TITLE
high cpu usage

### ISSUE THREAD

**Issue by yazansayed** [ryanckulp/twitter_ad_blocker#43]
the task manager shows that the twitter page is hogging a whole cpu core, and the problem is solved when 
i disable the extension.. if you need logs tell me how

**Comment by Jamie-Landeg-Jones** [comment]
Yep, same here. Scrolling down the page with the cursor keys is really jerky and unusable. A shame.

**Comment by ryanckulp** [comment]
i believe you that you are seeing strange CPU spikes with the extension enabled, but it's a basic tool that does a fraction of many website homepages in terms of client-side (JavaScript) computation. going to close this because i can't reproduce.
