### ISSUE TITLE
Doesn't block/change anything anymore since twitter redirected its url to x.com

### ISSUE THREAD

**Issue by nokel** [ryanckulp/twitter_ad_blocker#46]
I just went onto twitter today and everything that I've changed through the addon has been unchanged back to the new "default", it seems to be linked to the Twitter url because changing the vpn location to australia makes it keep my addon settings as twitter.com doesn't redirect yet.

**Comment by ryanckulp** [comment]
sorry, i'm not understanding what you mean. i just check on my browser (Chrome, USA Twitter) and it's indeed hiding them with no issues:

![image](https://github.com/ryanckulp/twitter_ad_blocker/assets/3083888/afb0133c-60ed-4776-bf2a-654d1d8df054)

are you saying that Twitter Australia is using something like `x.com.au` now? happy to investigate further.

**Comment by nokel** [comment]
I'm using vivaldi as the browser and PIA to connect to twitter, currently when I use "NZ Wellington" and go to twitter.com it redirects to x.com and the add-on doesn't change anything it's supposed to be changin:.

![image](https://github.com/ryanckulp/twitter_ad_blocker/assets/13248734/074b6c01-5b8e-4ec5-a26a-40b9e0a8f12c)

however, yesterday and this morning when I used Australia (either Melbourne or Sydney) it didn't redirect and the add-on worked fine and did everything expected... however upon checking just now it does the same as New Zealand... that being said, when I choose Singapore it doesn't redirect and works fine

![image](https://github.com/ryanckulp/twitter_ad_blocker/assets/13248734/ede80edb-f26f-40b1-8998-860a7916b72a)

turning the vpn off also makes the website redirect to x.com and the addon not work as well.

![image](https://github.com/ryanckulp/twitter_ad_blocker/assets/13248734/50a981c3-6f45-41fe-8999-5eac7e7131ec)

**Comment by nokel** [comment]
Oh, no, I'm sorry, I've accidentally mistaken this add-on which only removes adverts from twitter for another that changes twitter's look to before its x branding, please ignore me.
