### ISSUE TITLE
Remove new "Subscribe to Premium" and "Go add free"

### ISSUE THREAD

**Issue by Grsmto** [ryanckulp/twitter_ad_blocker#50]
Seems like they just added 2 new ad block for their premium service. Would be cool if we could get rid of those!

Thanks!

**Comment by ryanckulp** [comment]
thanks, this is now done via https://github.com/ryanckulp/twitter_ad_blocker/commit/d87c37eb2c722396abdaa0f5cc5b41c23a089de6 and https://github.com/ryanckulp/twitter_ad_blocker/commit/1fe4a06e0cf24c4a01733cfb286f2206bcc5ffdf. give Chrome a day or 2 to publish the new package.
