### ISSUE TITLE
Great work! Now if you could just...

### ISSUE THREAD

**Issue by jhoneill** [ryanckulp/twitter_ad_blocker#9]
Add optional blocking of any of "what's happening", "who to follow" and "Topics to follow" that would be a splendid enhancement.

**Comment by 0xleaf** [comment]
Not intended as spam but i think you might find [twitter-mod.js](https://github.com/0xleaf/twitter-mod.js#readme) useful for that. It allows certain features in the Twitter UI to be turned on or off. I was inspired by this project to create it. It's not on the webstore - you'd have to load it as a developer extension.
